### PR TITLE
Upgrade NServiceBus 8

### PR DESCRIPTION
**Pull request by twenzel**
Upgrade to NServiceBus 8 due to some interface changes.
Support Net472 also (Like NServiceBus)

### CODE REVIEW

**Comment by SimonCropp** [comment]
just to confirm all devs (using NSB) at your company are sponsors https://github.com/NServiceBusExtensions/Home#community-backed

**Comment by SimonCropp** [comment]
so you are the only developer at your company using nservicebus?

**Comment by SimonCropp** [comment]
@twenzel bump?

**Comment by twenzel** [comment]
I'm the only one using this extension in my extension.

**Pull request merged**
